### ISSUE TITLE
A few issues, mainly with wrong aim positions

### ISSUE THREAD

**Issue by napo1emon** [andtheherois/3DSS-LEWD-FAMAS#1]
I checked all three rifles and have this to report:

### wpn_famas_f1
no issues

### wpn_famas_commando
eots ok/ laser ok
barska **too close**/ laser ok
acog ok/ laser ok
c-more **a little too close**/ laser ok
eot ok/ laser ok
t12 ok/ laser ok
cqbss **wrong position**/ laser ok
pn-23 **wrong position**/ laser ok
specter ok/ laser ok
	
### wpn_famas_felin
irons ok/ no alt
eots ok/ alt aim wrong (it tries to use the irons but they're obstructed); turn off alt aim in weapon ltx
barska ok/ irons ok but why use them? better turn off alt aim
acog ok/ irons blocked; turn off or **make it use acog's irons**
c-more ok/ irons blocked; turn off
eot ok/ irons blocked; turn off
t12 ok/ irons blocked; turn off
cqbss ok/ irons blocked; turn off
pn-23 ok/ irons blocked; turn off
specter ok/ irons blocked; turn off or **make it use Specter's irons**

So what I did was set the `use_alt_aim_hud = false` parameters in _w_famas_felin.ltx_ and _mod_system_3DSS_lewd_famas.ltx_ (felin only) and it did the trick for that gun. Probably could utilize the alt aim on acog and specter iron sights with some repositioning, up to you. Commando still needs work.
### Lesser issues:
+ SpecterDR has old zoom switch with the black area sliding from side to side. Could use an update to match the base GAMMA weapons behavior.
+ EOTECH uses the old model (eot) with just one reticle, so using Mark Switch gives empty view for 5 clicks and the reticle after the 6th click. That's actually an issue with MarkSwitch persisting in the whole game, easily fixable in _mod_system_markswitch_weapons_default.ltx_

```
![eot]
	ms_count = 6 ;should be 1 since there are no more reticle choices
```

+ The metallic textures look too shiny, like someone painted them high gloss. Are you able to tone it down? Maybe there's a shader setting that controls the shininess?

**Comment by andtheherois** [comment]
fixed most of this. Not bothering with the red dot positions for now. fixed laser aim for felin. added config for specter step zoom. fixed the red dots for use with mark switch. Nothing i can do about the textures.
